name: Generate Bomberman Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Brunoverly77
          outputs: |
            dist/bomberman.svg?renderer=tetris
            dist/bomberman-dark.svg?renderer=tetris&palette=github-dark
